### ISSUE TITLE
[Adobe XD]アプリデザインの作成

### ISSUE THREAD

**Issue by kanon-k4** [jphacks/D_2017#11]
## 背景
検温デバイスと認証用カードの登録に必要なスマートフォンアプリのデザインを完成させる

## ゴール
- [x] デザインの完成
- [x] PNGデータ等で共有する

**Comment by kanon-k4** [comment]
## UIデザイン
Adobe XDで作成しました。以下のリンクから確認・コメントできます。

https://xd.adobe.com/view/f04cb295-f6b9-4d14-8cee-4c9a636b03d1-a51f/

**Comment by kanon-k4** [comment]
## 修正
- チュートリアル１の文言を修正
- 各部屋管理メニューを修正
  - ICカードリーダ管理を削除
  - 体温上限編集を追加
  - 部屋名編集を追加

**Comment by greenlaver** [comment]
- https://github.com/jphacks/D_2017/issues/5#issuecomment-720614571 の再計測体温申告画面がない
- 手で体温情報を入力する画面がない
