### ISSUE TITLE
RDSの設定をする

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [jphacks/D_2017#15]
## ゴール
* プロキシをかまして Lambda から叩けるようにする

**Comment by Yukiho-YOSHIEDA** [comment]
参考サイト
https://qiita.com/G-awa/items/b9138cc1c9e4867a905e

**Comment by 3to5thpower** [comment]
11月4日10:30までによろしくおねがいします

**Comment by greenlaver** [comment]
- 串の設定でターゲットのRDSインスタンス設定し忘れ
- Lambdaのendpointがproxy向いてなかった

の2つを解決して無事動いたっぽいのでclose
