### ISSUE TITLE
[API設計] デザイン/ユースフローを反映させたAPI一覧の完成

### ISSUE THREAD

**Issue by greenlaver** [jphacks/D_2017#5]
## 背景
@3to5thpower に設計内容を引き継ぐため、Wikiの[API一覧](https://github.com/jphacks/D_2017/wiki/API%E4%B8%80%E8%A6%A7)に反映させる。まだ足りてないので。

## 実装要件
- [x] アプデ系(?)APIを生やす
- [x] 部屋に対するルール（最大人数、体温ルールなど）設定
- [x] 部屋に属するメンバの情報（入退室状況、承認済みメンバ）取得
- [x] 体温計測、発熱の有無についての状態を2値から4状態へ（**要検討**）

**Comment by greenlaver** [comment]
4状態の話は正直どっちがいいのかわかっていない
（4状態は鯖側で持つか、あるいはアプリ側で持って鯖では許可/拒否のboolにするのか）
<img width="337" alt="スクリーンショット 2020-11-03 0 15 13" src="https://user-images.githubusercontent.com/24975540/97884750-d1966c80-1d69-11eb-9a0e-0a34e11b70ba.png">

**Comment by Yukiho-YOSHIEDA** [comment]
4状態はアプリ側で通知してあげればよい？
「行かへんほうがええで」みたいな

**Comment by Yukiho-YOSHIEDA** [comment]
No Dataの扱いが難しいところ
部屋によってポリシーが必要？
許可するレベルを管理者が決めるみたいな [OPTIONAL]

**Comment by Yukiho-YOSHIEDA** [comment]
一応部屋のアプデは設計したけど、他に何がいるんだろうか？
機器はサーバに登録しないよね？

**Comment by Yukiho-YOSHIEDA** [comment]
一応作業自体は終わったと思われ
@greenlaver がOKだったらCloseで

**Comment by greenlaver** [comment]
https://github.com/jphacks/D_2017/issues/5#issuecomment-720563214
> No Dataの扱いが難しいところ
> 部屋によってポリシーが必要？
> 許可するレベルを管理者が決めるみたいな [OPTIONAL]

過去2週間分についてデータ欠損があっても許可するか否かは、ルーム管理者が選べるということかしら。
だとすると、それもまたルームの制約ルールに項目として必要かと。

**Comment by greenlaver** [comment]
https://github.com/jphacks/D_2017/issues/5#issuecomment-720571742
> 一応部屋のアプデは設計したけど、他に何がいるんだろうか？
> 機器はサーバに登録しないよね？

機器登録できると、体温計測記録のデータに「どの計測機で計ったか」がわかるので欲しいかも？
機器を登録するかは、どのレベルまでデータを鯖に保存するかによりますが。

仮に感染者が出た場合、記録を提出する必要があるなら、計測データは
- When（いつ計ったか）
- What（何度だったか）
- Who（誰の記録か）
- How（どの機械で計ったか）

が必要でしょうか

**Comment by Yukiho-YOSHIEDA** [comment]
それをやってると実装が間に合わなくなるから Backlog に積んでおくのがベスト？

**Comment by greenlaver** [comment]
実装コスト高いすか

**Comment by Yukiho-YOSHIEDA** [comment]
> [#5 (comment)](https://github.com/jphacks/D_2017/issues/5#issuecomment-720571742)
> 機器登録できると、体温計測記録のデータに「どの計測機で計ったか」がわかるので欲しいかも？
> 機器を登録するかは、どのレベルまでデータを鯖に保存するかによりますが。
> 
> 仮に感染者が出た場合、記録を提出する必要があるなら、計測データは
> 
> * When（いつ計ったか）
> * What（何度だったか）
> * Who（誰の記録か）
> * How（どの機械で計ったか）
> 
> が必要でしょうか

**Comment by greenlaver** [comment]
https://github.com/jphacks/D_2017/issues/5#issuecomment-720575791
> それをやってると実装が間に合わなくなるから Backlog に積んでおくのがベスト？

どれの話だ...

**Comment by Yukiho-YOSHIEDA** [comment]
そもそもAPIの数が多すぎる

**Comment by Yukiho-YOSHIEDA** [comment]
https://github.com/jphacks/D_2017/issues/5#issuecomment-720575764
機器を登録する場合、PKになるものが存在する？
Macアドレスって本当にぶつからない？

**Comment by greenlaver** [comment]
https://github.com/jphacks/D_2017/issues/5#issuecomment-720577319
> [#5 (comment)](https://github.com/jphacks/D_2017/issues/5#issuecomment-720575764)
> 機器を登録する場合、PKになるものが存在する？
> Macアドレスって本当にぶつからない？

MACが衝突しない保証はないです。そのためにtoken発行できないかね〜みたいな話をしていた
（これはミーティングで言い忘れましたすまん）

uniqueなIDあるいはtoken付与するなら、管理者がルーム作成した後Reader登録するので、その紐付けタイミングで発行かしら

**Comment by greenlaver** [comment]
`部屋情報更新` の**Method**が書いてねーです（POST?PUT?）

**Comment by greenlaver** [comment]
## 4状態
`Warning` が出た時点で、ユーザに体温計測を促し、正確な体温を申告させる。

![IMG_D51CD07C5A36-1](https://user-images.githubusercontent.com/24975540/97899136-3b1f7680-1d7c-11eb-99a5-f4ff2a9cbcbb.jpeg)

## Readerの識別/認可
AWS IoT + Cognitoでいい感じにできないか検討

## 体温計の個体識別
Cognitoでtoken/ID発行機能があればそれを使う。
なければMACで乗り切る
