### ISSUE TITLE
AWSのアカウントを発行する

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [jphacks/D_2017#9]
## 背景
AWSのアカウントがなければ話にならんかったわ

## ゴール
わいの分と @3to5thpower くんの分をとりあえず作る

**Comment by greenlaver** [comment]
IoT用にワイのIAMもくれ

**Comment by Yukiho-YOSHIEDA** [comment]
おわおわり

**Comment by greenlaver** [comment]
Cognitoのユーザプール、オハイオ(us-east-2)じゃなくて東京リージョン(northeast-1)で作って

**Comment by greenlaver** [comment]
よくみたら #8 があったのでそっちに移動
